apiVersion: v1
kind: Pod
metadata:
  name: gpu-vectoradd-test
  namespace: default
spec:
  restartPolicy: Never
  runtimeClassName: nvidia
  containers:
  - name: cuda-vectoradd
    image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.7.1-ubuntu20.04
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        nvidia.com/gpu: 1
    command: ["/bin/sh"]
    args: ["-c", "while true; do /cuda-samples/vectorAdd; sleep 2; done"]
